/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:263: UserWarning: Feature 0 is constant and will be replaced with 0.
  warnings.warn(
/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:263: UserWarning: Feature 0 is constant and will be replaced with 0.
  warnings.warn(
#############
Data loaded
#############
 20%|██        | 1/5 [15:58<1:03:52, 958.01s/it]
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pgmpy/estimators/BayesianEstimator.py", line 110, in _get_node_param
    cpd = self.estimate_cpd(
          ^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pgmpy/estimators/BayesianEstimator.py", line 230, in estimate_cpd
    state_counts = self.state_counts(node, weighted=weighted)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pgmpy/estimators/base.py", line 272, in state_counts
    return super(ParameterEstimator, self).state_counts(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pgmpy/estimators/base.py", line 175, in state_counts
    state_counts = state_count_data.reindex(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/frame.py", line 5378, in reindex
    return super().reindex(
           ^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/generic.py", line 5607, in reindex
    return self._reindex_multi(axes, copy, fill_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/frame.py", line 5299, in _reindex_multi
    new_columns, col_indexer = self.columns.reindex(axes["columns"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 4422, in reindex
    indexer = self.get_indexer(
              ^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3953, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3974, in _get_indexer
    tgt_values = engine._extract_level_codes(  # type: ignore[union-attr]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 743, in pandas._libs.index.BaseMultiIndexCodesEngine._extract_level_codes
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 117. GiB for an array with shape (15, 1048576000) and data type uint64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home-mscluster/zschwark/Honours-Research/Cross_Validation/Random_cross_validation.py", line 75, in <module>
    log_likelihood = CrossValidation.perfrom_KfoldCrossValidation(folds = folds,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/Honours-Research/./CrossValidation.py", line 50, in perfrom_KfoldCrossValidation
    model.parameter_estimator(prior_type = kwargs.get("prior_type"), pseudo_counts=kwargs.get('pseudo_counts'), equivalent_sample_size = kwargs.get('PE_equivalent_sample_size') )
  File "/home-mscluster/zschwark/Honours-Research/./Models.py", line 84, in parameter_estimator
    parameters = parameter_estimator.get_parameters(prior_type=prior_type,equivalent_sample_size = equivalent_sample_size, pseudo_counts = pseudo_counts,  n_jobs=6)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/pgmpy/estimators/BayesianEstimator.py", line 119, in get_parameters
    parameters = Parallel(n_jobs=n_jobs)(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-mscluster/zschwark/miniconda3/envs/HonoursResearch/lib/python3.11/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 117. GiB for an array with shape (15, 1048576000) and data type uint64
